# Site settings
title: MinHye Joo
email: minhyj@pitzer.edu 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://MinHyeJoo.github.io" # the base hostname & protocol for your site
github_username: MinhyeJoo
encoding: UTF-8
# Build settings
markdown: kramdown
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DY0GNEVQRR"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DY0GNEVQRR');
</script>
