# Site settings
title: MinHye Joo
email: minhyj@pitzer.edu 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://MinHyeJoo.github.io" # the base hostname & protocol for your site
github_username: MinhyeJoo
encoding: UTF-8
# Build settings
markdown: kramdown
